version: '2'
services:
    demobootstrap-app:
        image: demobootstrap
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://demobootstrap-mysql:3306/demobootstrap?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    demobootstrap-mysql:
        extends:
            file: mysql.yml
            service: demobootstrap-mysql
